name: Upload-Deploy to site and Cloudfront

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
	
	
	- name: Install npm
	  run: npm install
	  
	- name: Build Site
	  run: npm run build
	
	
	
	
    #- name: Setup Python
	 # uses: actions/setup-python@v1
	  #with:
	  	#python-version: '3.x'
		
	#- name: Install AWS CommandLine Tools
	 # run: pip3 install awscli --upgrade --user
	
	- name: Configure AWS Creds
	  uses: aws-actions/configure-aws-credentials@v1
      with:
        #args: --acl public-read --follow-symlinks --delete
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        #SOURCE_DIR: 'public'      # optional: defaults to entire repository
		
	- name: Upload to S3 Bucket
	  run: aws s3 sync .s3//${{ secrets.AWS_S3_BUCKET }} --exclude ".git/*" --exclude ".github/*" --delete
	  
	- name: Invalidate CloudFront Cache
	  run aws cloudfront create-invalidation -- distribution-id ${{ secrets.AWS_CLOUDFRONT_KEY_ID }} --paths "/*"
	  
	  